# Generated by Django 4.2.23 on 2026-07-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='dia_descanso',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default='DOM', max_length=3),
        ),
        migrations.AddField(
            model_name='barbero',
            name='dias_laborales',
            field=models.CharField(default='LUN,MAR,MIE,JUE,VIE,SAB', max_length=50),
        ),
        migrations.AddField(
            model_name='barbero',
            name='duracion_cita',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='barbero',
            name='jornada_fin',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='barbero',
            name='jornada_inicio',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='barbero',
            name='tiempo_entre_citas',
            field=models.IntegerField(default=15),
        ),
    ]
