# Generated by Django 6.1.1 on 2026-09-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitio',
            old_name='hero_imagen_1',
            new_name='hero_imagen_1_url',
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='hero_imagen_2',
            new_name='hero_imagen_2_url',
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='hero_imagen_3',
            new_name='hero_imagen_3_url',
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='nosotros_imagen',
            new_name='nosotros_imagen_url',
        ),
        migrations.AddField(
            model_name='sitio',
            name='hero_imagen_1_archivo',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitio',
            name='hero_imagen_1_fuente',
            field=models.CharField(choices=[('url', 'URL'), ('archivo', 'Archivo del dispositivo')], default='url', max_length=10),
        ),
        migrations.AddField(
            model_name='sitio',
            name='hero_imagen_2_archivo',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitio',
            name='hero_imagen_2_fuente',
            field=models.CharField(choices=[('url', 'URL'), ('archivo', 'Archivo del dispositivo')], default='url', max_length=10),
        ),
        migrations.AddField(
            model_name='sitio',
            name='hero_imagen_3_archivo',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitio',
            name='hero_imagen_3_fuente',
            field=models.CharField(choices=[('url', 'URL'), ('archivo', 'Archivo del dispositivo')], default='url', max_length=10),
        ),
        migrations.AddField(
            model_name='sitio',
            name='nosotros_imagen_archivo',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='sitio',
            name='nosotros_imagen_fuente',
            field=models.CharField(choices=[('url', 'URL'), ('archivo', 'Archivo del dispositivo')], default='url', max_length=10),
        ),
    ]
