# Generated by Django 6.1.1 on 2026-09-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_sitio_mapa_y_fachada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='mapa_embed_url',
            field=models.URLField(blank=True, default='', help_text='URL para incrustar (embed) la ubicación de Google Maps. En Google Maps: Compartir > Insertar un mapa > copiar solo el valor del atributo src del iframe.'),
        ),
    ]
