# Generated by Django 6.0.7 on 2026-08-24 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0024_cita_recordatorio_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acceso', models.TextField()),
                ('token_refresco', models.TextField()),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=200)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.CharField(max_length=500)),
                ('expiracion', models.DateTimeField(blank=True, null=True)),
                ('email_google', models.EmailField(blank=True, default='', max_length=254)),
                ('fecha_conexion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_google', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Google conectada',
                'verbose_name_plural': 'Cuentas de Google conectadas',
            },
        ),
        migrations.CreateModel(
            name='CitaEventoGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('event_id', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_google', to='citas.cita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_google_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Google Calendar por cita',
                'verbose_name_plural': 'Eventos de Google Calendar por cita',
                'unique_together': {('cita', 'usuario')},
            },
        ),
    ]
