# Generated by Django 6.0.8 on 2026-08-05 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_movimientoinventario_id_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5, message='El stock mínimo permitido es de 5 unidades.'), django.core.validators.MaxValueValidator(20, message='No se puede registrar más de 20 unidades de este producto.')]),
        ),
    ]
