# Generated by Django 6.0.7 on 2026-07-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0018_alter_cita_id_alter_servicio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
