# Generated by Django 6.0.7 on 2026-07-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0019_alter_cita_id_alter_servicio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_total',
            field=models.PositiveIntegerField(default=35),
        ),
    ]
