# Generated by Django 6.0.7 on 2026-08-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0021_remove_cita_duracion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_total',
            field=models.PositiveIntegerField(default=35),
        ),
    ]
