# Generated by Django 6.0.7 on 2026-08-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0022_cita_duracion_total'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cita',
            name='cita_unica_por_barbero',
        ),
    ]
