# Generated by Django 6.1.1 on 2026-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0024_cita_recordatorio_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='historial_archivado',
            field=models.BooleanField(default=False),
        ),
    ]
