# Generated by Django 6.1.1 on 2026-09-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0025_cita_historial_archivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='analisis_ia',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
