# Generated by Django 6.1.1 on 2026-09-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0026_cita_analisis_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.URLField(blank=True, default='', help_text='URL de la imagen del estilo o corte'),
        ),
    ]
