# Generated by Django 6.1.1 on 2026-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0027_suscriptornewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptornewsletter',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
