# Generated by Django 6.1.1 on 2026-09-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0028_alter_suscriptornewsletter_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.URLField(blank=True, default='', help_text='URL de la imagen del estilo o corte'),
        ),
    ]
