# Generated by Django 6.1.1 on 2026-09-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_suscripcionturno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
