# Generated by Django 6.0.7 on 2026-07-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0020_cita_duracion_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='duracion_total',
        ),
    ]
