# Generated by Django 6.1 on 2026-08-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0023_remove_cita_cita_unica_por_barbero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
